services:
    php_fpm:
        build:
            context: ./docker/php-fpm
            dockerfile: Dockerfile
        container_name: myapp_php_fpm
        restart: unless-stopped
        depends_on:
            - db
            - cache
        working_dir: /var/www/html
        networks:
            - bamaq
        volumes:
            - ./:/var/www/html

    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        container_name: myapp_nginx
        restart: unless-stopped
        depends_on:
            - php_fpm
        networks:
            - bamaq
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html

    db:
        image: mysql
        restart: always
        ports:
          - "3306:3306"
        environment:
          MYSQL_ROOT_PASSWORD: bamaq
          MYSQL_DATABASE: bamaq
          MYSQL_USER: bamaq
          MYSQL_PASSWORD: bamaq
        volumes:
          - .docker/dbdata:/var/lib/mysql
        networks:
          - bamaq

    cache:
          image: redis:7.4-alpine
          restart: always
          ports:
            - '6379:6379'
          command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
          volumes:
            - cache:/data
          networks:
            - bamaq
volumes:
    cache:
        driver: local
networks:
    bamaq:
        driver: bridge
