version: '3.3'
services:
  bamaq:
    build: ./
    container_name: nginx-bamaq
    ports:
      - 8000:80
    volumes:
      - ./:/usr/share/nginx/html
    restart: always
    networks:
      - bamaq

  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: bamaq
      MYSQL_DATABASE: bamaq
      MYSQL_USER: bamaq
      MYSQL_PASSWORD: bamaq
    volumes:
      - .docker/dbdata:/var/lib/mysql
    networks:
      - bamaq

networks:
  bamaq:
    driver: bridge
